stages:
  - docker
  - test


dockerize:
  stage: docker
  image: docker:stable

  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  when: manual
  
  services:
    - docker:dind

  before_script:
    - docker info

  script:
  - VERSION=0.6.0
  - docker login -u $CI_REGISTRY_USER -p $IMAGE_PUBLISH_TOKEN git.isw.uni-stuttgart.de:5000
  - docker build -t chhinze/libfranka:$VERSION --build-arg VERSION=$VERSION -f libfranka.Dockerfile .
  - docker tag chhinze/libfranka:$VERSION $CI_REGISTRY_IMAGE/libfranka:$VERSION
  - docker tag chhinze/libfranka:$VERSION $CI_REGISTRY_IMAGE/libfranka:latest
  - docker push $CI_REGISTRY_IMAGE/libfranka:$VERSION

unittests:
    stage: test
    image: $CI_REGISTRY_IMAGE/libfranka

    script:
    - mkdir -p build && cd build
    - cmake ..
    - make -j4 tests

